baseurl: "/"
url: "https://fermicoding.club"
theme: jekyll-theme-minimal
title: "Fermilab Coding Club"
description: "A repository of Coding Club events and code"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/updates/page:num/"
