theme: jekyll-theme-minimal
title: "Fermilab Coding Club"
description: "A repository of Coding Club events and code"
# logo: [Location of the logo]
# show_downloads: "true"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/updates/page:num/"
